services:
  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - fitness_ntwrk

  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  recipe-service:
    build: recipe-service
    image: fitness_recipe-service:1.0.0
    networks:
      - fitness_ntwrk
    depends_on:
      - recipe-db

  recipe-db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./recipe-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recipe
    networks:
      - fitness_ntwrk

  user-service:
    build: user-service
    image: fitness_user-service:1.0.0
    networks:
      - fitness_ntwrk
    depends_on:
      - user-db

  user-db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user
    networks:
      - fitness_ntwrk

  email-service:
    build: email-service
    image: fitness_email-service:1.0.0
    networks:
      - fitness_ntwrk
    depends_on:
      - email-db

  email-db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./email-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: email
    networks:
      - fitness_ntwrk

  proxy:
    build: proxy
    image: fitness_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk

networks:
  fitness_ntwrk:
    name: fitness_ntwrk
