spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: data
  datasource:
    url: jdbc:postgresql://user-db:5432/user
    username: root
    password: root
    driverClassName: org.postgresql.Driver

user-service:
  mail-service:
    uri: http://email-service:8080/api/v1/mail

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy
