spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: change_me
    password: change_me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false

  datasource:
    url: jdbc:postgresql://email-db:5432/email
    username: root
    password: root
    driverClassName: org.postgresql.Driver
